'^/wp-admin$':
  to: "/wp/wp-admin/"
  regexp: true
'^/wp-admin/(.*)':
  to: "/wp/wp-admin/$1"
  regexp: true
'^/donate/?$': 
  to: 'https://alumni.colby.edu/center-for-small-town-jewish-life-giving-page/'   
  regexp: true
  code: 301
'^/about/?$': 
  to: '/who-we-are/'   
  regexp: true
  code: 301
'^/about/leadership/?$': 
  to: '/who-we-are/'   
  regexp: true
  code: 301
'^/about/national-advisory-board/?$': 
  to: '/who-we-are/'   
  regexp: true
  code: 301
'^/about/student-jewish-leadership-fellows/student-leadership-fellows/?$': 
  to: '/colby-and-waterville/'   
  regexp: true
  code: 301
'^/about/rabbinical-student-fellows/?$': 
  to: '/national/rabbinical-student-fellows/'   
  regexp: true
  code: 301
'^/programs/?$': 
  to: '/maine/'   
  regexp: true
  code: 301
'^/programs/funtensive-2/?$': 
  to: '/maine/funtensive-2/'   
  regexp: true
  code: 301
'^/programs/jewish-youth-connection/?$': 
  to: '/maine/jewish-youth-connection/'   
  regexp: true
  code: 301
'^/programs/lifelong-learning/?$': 
  to: '/maine/lifelong-learning/'   
  regexp: true
  code: 301
'^/programs/shlichei-tzibur-training/?$': 
  to: '/maine/lifelong-learning/'   
  regexp: true
  code: 301
'^/programs/lifelong-learning/?$': 
  to: '/shlichei-tzibur-training/'   
  regexp: true
  code: 301
'^/programs/the-lipman-lecture/?$': 
  to: '/colby-and-waterville/the-lipman-lecture/'   
  regexp: true
  code: 301
'^/makom/?$': 
  to: '/national/makom/'   
  regexp: true
  code: 301
'^/news-updates/?$': 
  to: '/press/'   
  regexp: true
  code: 301